[colors]
# Colores por defecto
[colors.primary]
background = "#1E1E1E"
foreground = "#E6E6E6"

# Cursor
[colors.cursor]
text = "#1E1E1E"
cursor = "#D9CC8F"

# Colores Normales
[colors.normal]
black   = "#1E1E1E"
red     = "#BF5F55"
green   = "#D9CC8F" # Usando beige como verde para mantener la calidez
yellow  = "#D9CC8F"
blue    = "#7A7A7A" # Usando gris medio como azul (neutro)
magenta = "#B26E72"
cyan    = "#B26E72" # Reutilizando rosa
white   = "#E6E6E6"

# Colores Brillantes
[colors.bright]
black   = "#4A4A4A"
red     = "#BF5F55"
green   = "#D9CC8F"
yellow  = "#D9CC8F"
blue    = "#7A7A7A"
magenta = "#B26E72"
cyan    = "#B26E72"
white   = "#FFFFFF"