[window]
padding = { x = 20, y = 20 } # Espacio interno para que el texto no pegue al borde
decorations = "none"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0

[colors]
# Colores primarios
[colors.primary]
background = "#1A2E12" # Dark Jungle Green
foreground = "#D2D5DE" # Light Silver

# Colores normales
[colors.normal]
black   = "#1A2E12"
red     = "#A87CC7" # Usamos African Violet como color destacado
green   = "#658751" # Axolotl
yellow  = "#D2D5DE"
blue    = "#7F89E9" # Vista Blue
magenta = "#A87CC7"
cyan    = "#7F89E9"
white   = "#D2D5DE"